In [1]:
from Layers.conv import Conv2DLayer
import torch, torch.nn as nn

In [10]:
dummy_img_1 = torch.zeros((3,5,5))
dummy_img_2 = torch.arange(25).view((1,5,5))

In [11]:
conv_layer = Conv2DLayer(window_size=(3,3), stride=(1,1), channels_in=3, channels_out=8)
out1 = conv_layer(dummy_img_1)
assert out1.shape==(8,3,3)

In [12]:
conv_layer = Conv2DLayer(window_size=(3,3), stride=(2,2), channels_in=3, channels_out=8)
out2 = conv_layer(dummy_img_1)
assert out2.shape==(8,2,2)

In [13]:
conv_layer = Conv2DLayer(window_size=(3,3), stride=(2,2), channels_in=1, channels_out=1)
conv_layer.weights = torch.ones((1,1,3,3))
out3 = conv_layer(dummy_img_2)
out3

tensor([[[ 54.,  72.],
         [144., 162.]]])

In [14]:
dummy_img_2

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24]]])

In [16]:
conv_layer.grad_calc(torch.ones(out3.shape))

tensor([[[1., 1., 2., 1., 1.],
         [1., 1., 2., 1., 1.],
         [2., 2., 4., 2., 2.],
         [1., 1., 2., 1., 1.],
         [1., 1., 2., 1., 1.]]])

In [17]:
conv_layer.w_grads

tensor([[[[24., 28., 32.],
          [44., 48., 52.],
          [64., 68., 72.]]]])

In [18]:
conv_layer.b_grads

tensor([[4.]])