# Conv2D Layer

In [1]:
from Layers.conv import Conv2DLayer
import torch, torch.nn as nn

In [2]:
dummy_img_1 = torch.zeros((2,3,5,5))
dummy_img_2 = torch.arange(50).view((2,1,5,5))

In [3]:
conv_layer = Conv2DLayer(window_size=(3,3), stride=(1,1), channels_in=3, channels_out=8)
out1 = conv_layer(dummy_img_1)
assert out1.shape==(2,8,3,3)

In [4]:
conv_layer = Conv2DLayer(window_size=(3,3), stride=(2,2), channels_in=3, channels_out=8)
out2 = conv_layer(dummy_img_1)
assert out2.shape==(2,8,2,2)

In [5]:
conv_layer = Conv2DLayer(window_size=(3,3), stride=(2,2), channels_in=1, channels_out=1)
conv_layer.weights = torch.ones((1,1,3,3))
out3 = conv_layer(dummy_img_2)
out3

tensor([[[[ 54.,  72.],
          [144., 162.]]],


        [[[279., 297.],
          [369., 387.]]]])

In [6]:
dummy_img_2

tensor([[[[ 0,  1,  2,  3,  4],
          [ 5,  6,  7,  8,  9],
          [10, 11, 12, 13, 14],
          [15, 16, 17, 18, 19],
          [20, 21, 22, 23, 24]]],


        [[[25, 26, 27, 28, 29],
          [30, 31, 32, 33, 34],
          [35, 36, 37, 38, 39],
          [40, 41, 42, 43, 44],
          [45, 46, 47, 48, 49]]]])

In [7]:
conv_layer.grad_calc(torch.ones(out3.shape))

tensor([[[[1., 1., 2., 1., 1.],
          [1., 1., 2., 1., 1.],
          [2., 2., 4., 2., 2.],
          [1., 1., 2., 1., 1.],
          [1., 1., 2., 1., 1.]]],


        [[[1., 1., 2., 1., 1.],
          [1., 1., 2., 1., 1.],
          [2., 2., 4., 2., 2.],
          [1., 1., 2., 1., 1.],
          [1., 1., 2., 1., 1.]]]])

In [8]:
conv_layer.w_grads

tensor([[[[148., 156., 164.],
          [188., 196., 204.],
          [228., 236., 244.]]]])

In [9]:
conv_layer.b_grads

tensor([8.])

In [14]:
dummy_img_1 = torch.zeros((2,3,5,5))
conv_layer = Conv2DLayer(window_size=(3,3), stride=(3,3), channels_in=3, channels_out=8)
out1 = conv_layer(dummy_img_1)

In [15]:
out1.shape

torch.Size([2, 8, 1, 1])

# Dropout Layer

In [10]:
import torch
from Layers.dropout import Dropout

In [11]:
X = torch.ones((4,5))
dropout = Dropout(dp_rate=0.0)
dropout(X)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [12]:
X = torch.ones((4,5))
dropout = Dropout(dp_rate=1.0)
dropout(X)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [13]:
X = torch.ones((4,5))
dropout = Dropout(dp_rate=0.5)
dropout(X)

tensor([[1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.]])

# MaxPool2D

In [1]:
import torch
from Layers.max_pool import MaxPooling2D

In [2]:
maxpool = MaxPooling2D()

In [9]:
X = torch.rand((2,1,5,5))
maxpool(X), X

(tensor([[[[0.9930, 0.9675],
           [0.7300, 0.9832]]],
 
 
         [[[0.9641, 0.5186],
           [0.8110, 0.9801]]]]),
 tensor([[[[0.3449, 0.7124, 0.2184, 0.9675, 0.4344],
           [0.5361, 0.9930, 0.3806, 0.4275, 0.3641],
           [0.5314, 0.2649, 0.9832, 0.3472, 0.3024],
           [0.7300, 0.4045, 0.9172, 0.8592, 0.9061],
           [0.3196, 0.5183, 0.0088, 0.9914, 0.0204]]],
 
 
         [[[0.4563, 0.3775, 0.2098, 0.1555, 0.9832],
           [0.3222, 0.9641, 0.1323, 0.5186, 0.9860],
           [0.6151, 0.8110, 0.2046, 0.1952, 0.3993],
           [0.6394, 0.2493, 0.7186, 0.9801, 0.7581],
           [0.4963, 0.0907, 0.6783, 0.2511, 0.3731]]]]))

In [10]:
maxpool.max_idx

[[tensor(1), tensor(1)],
 [tensor(0), tensor(1)],
 [tensor(1), tensor(0)],
 [tensor(0), tensor(0)],
 [tensor(1), tensor(1)],
 [tensor(1), tensor(1)],
 [tensor(0), tensor(1)],
 [tensor(1), tensor(1)]]

In [11]:
maxpool.grad_calc(torch.ones(2,1,2,2))

tensor([[[[0., 0., 0., 1., 0.],
          [0., 1., 0., 0., 0.],
          [0., 0., 1., 0., 0.],
          [1., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 1., 0., 1., 0.],
          [0., 1., 0., 0., 0.],
          [0., 0., 0., 1., 0.],
          [0., 0., 0., 0., 0.]]]])